In [1]:
import numpy as np
import pandas as pd


## Read the data

In [103]:
housing_data = pd.read_csv("./data/Ames_Housing_Sales.csv")

In [104]:
housing_data.head()

1stFlrSF  2ndFlrSF  3SsnPorch Alley  BedroomAbvGr BldgType BsmtCond  \
0     856.0     854.0        0.0  None             3     1Fam       TA   
1    1262.0       0.0        0.0  None             3     1Fam       TA   
2     920.0     866.0        0.0  None             3     1Fam       TA   
3     961.0     756.0        0.0  None             3     1Fam       Gd   
4    1145.0    1053.0        0.0  None             4     1Fam       TA   

  BsmtExposure  BsmtFinSF1  BsmtFinSF2  ... ScreenPorch Street  TotRmsAbvGrd  \
0           No       706.0         0.0  ...         0.0   Pave             8   
1           Gd       978.0         0.0  ...         0.0   Pave             6   
2           Mn       486.0         0.0  ...         0.0   Pave             6   
3           No       216.0         0.0  ...         0.0   Pave             7   
4           Av       655.0         0.0  ...         0.0   Pave             9   

   TotalBsmtSF Utilities  WoodDeckSF YearBuilt YearRemodAdd YrSold SalePrice  
0        856.0    AllPub         0.0      2003         2003   2008  208500.0  
1       1262.0    AllPub       298.0      1976         1976   2007  181500.0  
2        920.0    AllPub         0.0      2001         2002   2008  223500.0  
3        756.0    AllPub         0.0      1915         1970   2006  140000.0  
4       1145.0    AllPub       192.0      2000         2000   2008  250000.0  

[5 rows x 80 columns]

In [4]:
housing_data.shape

(1379, 80)

In [5]:
housing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1379 entries, 0 to 1378
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   1stFlrSF       1379 non-null   float64
 1   2ndFlrSF       1379 non-null   float64
 2   3SsnPorch      1379 non-null   float64
 3   Alley          1379 non-null   object 
 4   BedroomAbvGr   1379 non-null   int64  
 5   BldgType       1379 non-null   object 
 6   BsmtCond       1379 non-null   object 
 7   BsmtExposure   1379 non-null   object 
 8   BsmtFinSF1     1379 non-null   float64
 9   BsmtFinSF2     1379 non-null   float64
 10  BsmtFinType1   1379 non-null   object 
 11  BsmtFinType2   1379 non-null   object 
 12  BsmtFullBath   1379 non-null   int64  
 13  BsmtHalfBath   1379 non-null   int64  
 14  BsmtQual       1379 non-null   object 
 15  BsmtUnfSF      1379 non-null   float64
 16  CentralAir     1379 non-null   object 
 17  Condition1     1379 non-null   object 
 18  Conditio

In [ ]:
## Dependent Variable - SalesPrice
## Independent Variable - All other Columns


## Data Preprocessing

In [6]:
housing_data.isna().sum()

1stFlrSF        0
2ndFlrSF        0
3SsnPorch       0
Alley           0
BedroomAbvGr    0
               ..
WoodDeckSF      0
YearBuilt       0
YearRemodAdd    0
YrSold          0
SalePrice       0
Length: 80, dtype: int64

In [7]:
housing_data.corr()

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  \
1stFlrSF       1.000000 -0.223710   0.053200      0.104870    0.446596   
2ndFlrSF      -0.223710  1.000000  -0.026654      0.507574   -0.142969   
3SsnPorch      0.053200 -0.026654   1.000000     -0.026018    0.023903   
BedroomAbvGr   0.104870  0.507574  -0.026018      1.000000   -0.118036   
BsmtFinSF1     0.446596 -0.142969   0.023903     -0.118036    1.000000   
BsmtFinSF2     0.094006 -0.106641  -0.031442     -0.007734   -0.054966   
BsmtFullBath   0.251470 -0.174004  -0.001370     -0.158250    0.647400   
BsmtHalfBath  -0.000641 -0.021530   0.035611      0.046327    0.060852   
BsmtUnfSF      0.311394 -0.006450   0.020335      0.148676   -0.502954   
EnclosedPorch -0.051324  0.064856  -0.036961      0.051674   -0.096743   
Fireplaces     0.402572  0.192708   0.006232      0.123763    0.253887   
FullBath       0.366051  0.417049   0.033290      0.357911    0.044227   
GarageArea     0.495321  0.128010   0.023664      0.087321    0.289128   
GarageCars     0.439740  0.185903   0.023932      0.117522    0.201996   
GarageYrBlt    0.233449  0.070832   0.023544     -0.064518    0.153484   
GrLivArea      0.554620  0.683441   0.017073      0.512312    0.208016   
HalfBath      -0.145909  0.616881  -0.008238      0.237027   -0.007579   
KitchenAbvGr   0.076861  0.039845  -0.023486      0.170682   -0.065825   
LotArea        0.291478  0.046253   0.018443      0.119746    0.210145   
LotFrontage    0.379671  0.065102   0.036396      0.234235    0.226843   
LowQualFinSF  -0.018854  0.045547  -0.000254      0.056561   -0.050021   
MSSubClass    -0.253983  0.307616  -0.043958     -0.058433   -0.067904   
MasVnrArea     0.332127  0.173013   0.015923      0.108731    0.253765   
MiscVal       -0.015264  0.012266   0.000504      0.007535    0.006846   
MoSold         0.030181  0.033088   0.029868      0.042283   -0.017515   
OpenPorchSF    0.224826  0.203821  -0.007242      0.081911    0.120338   
OverallCond   -0.147171  0.016720   0.026735      0.014985   -0.050818   
OverallQual    0.467425  0.286109   0.024314      0.081714    0.223690   
PoolArea       0.132555  0.082247  -0.008465      0.075833    0.141615   
ScreenPorch    0.080980  0.037506  -0.033367      0.048004    0.056216   
TotRmsAbvGrd   0.396528  0.612217  -0.009653      0.665963    0.044389   
TotalBsmtSF    0.822469 -0.197325   0.034016      0.023909    0.521366   
WoodDeckSF     0.225905  0.089892  -0.036409      0.052647    0.194729   
YearBuilt      0.258161  0.017152   0.026285     -0.071794    0.229643   
YearRemodAdd   0.235044  0.128197   0.043737     -0.067375    0.114668   
YrSold        -0.016442 -0.030946   0.019484     -0.031269    0.017754   
SalePrice      0.594935  0.313336   0.039226      0.164655    0.375563   

               BsmtFinSF2  BsmtFullBath  BsmtHalfBath  BsmtUnfSF  \
1stFlrSF         0.094006      0.251470     -0.000641   0.311394   
2ndFlrSF        -0.106641     -0.174004     -0.021530  -0.006450   
3SsnPorch       -0.031442     -0.001370      0.035611   0.020335   
BedroomAbvGr    -0.007734     -0.158250      0.046327   0.148676   
BsmtFinSF1      -0.054966      0.647400      0.060852  -0.502954   
BsmtFinSF2       1.000000      0.159399      0.074146  -0.214549   
BsmtFullBath     0.159399      1.000000     -0.153387  -0.425382   
BsmtHalfBath     0.074146     -0.153387      1.000000  -0.096290   
BsmtUnfSF       -0.214549     -0.425382     -0.096290   1.000000   
EnclosedPorch    0.045387     -0.041446     -0.002122   0.001498   
Fireplaces       0.039251      0.143772      0.028365   0.047401   
FullBath        -0.089523     -0.081391     -0.066631   0.294838   
GarageArea      -0.047320      0.192149     -0.043608   0.201121   
GarageCars      -0.075257      0.135944     -0.041302   0.244263   
GarageYrBlt     -0.088011      0.124553     -0.077464   0.190708   
GrLivArea       -0.019636      0.037976     -0.018373   0.226614   
HalfBath        -0.035581     -0.042676     -0

In [32]:
housing_data_num = housing_data
for col in housing_data_num.columns:
    #print(housing_data_num[col].dtypes)
    if housing_data_num[col].dtypes == 'object':
        housing_data_num.drop(col, inplace = True , axis = 1)
housing_data_num.info()   

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1379 entries, 0 to 1378
Data columns (total 37 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   1stFlrSF       1379 non-null   float64
 1   2ndFlrSF       1379 non-null   float64
 2   3SsnPorch      1379 non-null   float64
 3   BedroomAbvGr   1379 non-null   int64  
 4   BsmtFinSF1     1379 non-null   float64
 5   BsmtFinSF2     1379 non-null   float64
 6   BsmtFullBath   1379 non-null   int64  
 7   BsmtHalfBath   1379 non-null   int64  
 8   BsmtUnfSF      1379 non-null   float64
 9   EnclosedPorch  1379 non-null   float64
 10  Fireplaces     1379 non-null   int64  
 11  FullBath       1379 non-null   int64  
 12  GarageArea     1379 non-null   float64
 13  GarageCars     1379 non-null   int64  
 14  GarageYrBlt    1379 non-null   float64
 15  GrLivArea      1379 non-null   float64
 16  HalfBath       1379 non-null   int64  
 17  KitchenAbvGr   1379 non-null   int64  
 18  LotArea 

In [79]:
### Train Test Split: 

X = housing_data_num.drop('SalePrice', axis =1 )
Y = housing_data_num['SalePrice']

from sklearn.model_selection import train_test_split
X_train , X_test , Y_train, Y_test = train_test_split(X,Y, test_size = 0.25)

In [80]:
X_train.head(1)

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
180     864.0       0.0        0.0             3       390.0         0.0   

     BsmtFullBath  BsmtHalfBath  BsmtUnfSF  EnclosedPorch  ...  OverallCond  \
180             0             0      474.0            0.0  ...            7   

     OverallQual  PoolArea  ScreenPorch  TotRmsAbvGrd  TotalBsmtSF  \
180            5       0.0          0.0             5        864.0   

     WoodDeckSF  YearBuilt  YearRemodAdd  YrSold  
180         0.0       1972          1972    2008  

[1 rows x 36 columns]

In [81]:
Y_train.head(1)

180    127000.0
Name: SalePrice, dtype: float64

In [82]:
X_train.shape , Y_train.shape

((1034, 36), (1034,))

In [83]:
X_test.shape , Y_test.shape

((345, 36), (345,))

In [84]:
X_train.head()

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
180      864.0       0.0        0.0             3       390.0         0.0   
1374     953.0     694.0        0.0             3         0.0         0.0   
521     1006.0    1040.0        0.0             3       866.0         0.0   
675      971.0       0.0        0.0             3       523.0         0.0   
211      483.0     504.0        0.0             2       321.0         0.0   

      BsmtFullBath  BsmtHalfBath  BsmtUnfSF  EnclosedPorch  ...  OverallCond  \
180              0             0      474.0            0.0  ...            7   
1374             0             0      953.0            0.0  ...            5   
521              1             0      132.0            0.0  ...            5   
675              0             0      448.0            0.0  ...            6   
211              0             0      162.0            0.0  ...            6   

      OverallQual  PoolArea  ScreenPorch  TotRmsAbvGrd  TotalBsmtSF  \
180             5       0.0          0.0             5        864.0   
1374            6       0.0          0.0             7        953.0   
521             7       0.0          0.0             8        998.0   
675             5       0.0          0.0             5        971.0   
211             6       0.0          0.0             5        483.0   

      WoodDeckSF  YearBuilt  YearRemodAdd  YrSold  
180          0.0       1972          1972    2008  
1374         0.0       1999          2000    2007  
521        320.0       2003          2004    2008  
675          0.0       1969          1969    2006  
211          0.0       1970          1970    2008  

[5 rows x 36 columns]

In [85]:
X_test.head()

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
298     1472.0       0.0        0.0             3      1036.0         0.0   
475      855.0     467.0        0.0             3       257.0       495.0   
998     1130.0    1054.0        0.0             3       936.0         0.0   
1079     672.0     252.0        0.0             2       348.0         0.0   
258     1560.0       0.0        0.0             3         0.0         0.0   

      BsmtFullBath  BsmtHalfBath  BsmtUnfSF  EnclosedPorch  ...  OverallCond  \
298              1             0      336.0            0.0  ...            5   
475              0             1      103.0            0.0  ...            5   
998              1             0      168.0            0.0  ...            5   
1079             1             0      324.0            0.0  ...            4   
258              0             0     1560.0            0.0  ...            5   

      OverallQual  PoolArea  ScreenPorch  TotRmsAbvGrd  TotalBsmtSF  \
298             7       0.0          0.0             6       1372.0   
475             6       0.0          0.0             6        855.0   
998             9       0.0          0.0            10       1104.0   
1079            4       0.0          0.0             5        672.0   
258             7       0.0          0.0             7       1560.0   

      WoodDeckSF  YearBuilt  YearRemodAdd  YrSold  
298        233.0       1980          1980    2009  
475        260.0       1974          1974    2009  
998          0.0       2008          2008    2009  
1079         0.0       1941          1950    2010  
258        100.0       2003          2003    2010  

[5 rows x 36 columns]

In [86]:
X_train['1stFlrSF']

180      864.0
1374     953.0
521     1006.0
675      971.0
211      483.0
         ...  
71      1086.0
157     1656.0
1325    1294.0
350     1120.0
853      807.0
Name: 1stFlrSF, Length: 1034, dtype: float64

In [89]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
X_train_transformed = sc.fit_transform(X_train)

In [91]:
X_train_transformed.shape

(1034, 36)

In [92]:
X_train_transformed

array([[-0.82471781, -0.80260864, -0.12151325, ..., -0.03177622,
        -0.66994182,  0.14963408],
       [-0.58926325,  0.7866583 , -0.12151325, ...,  0.88373321,
         0.70537943, -0.60144185],
       [-0.44904873,  1.57900175, -0.12151325, ...,  1.01936424,
         0.90185389,  0.14963408],
       ...,
       [ 0.31287164, -0.80260864, -0.12151325, ...,  1.12108751,
         1.00009112, -1.35251779],
       [-0.14745525,  0.26911604, -0.12151325, ..., -0.47257706,
        -1.30848382,  0.14963408],
       [-0.97551455,  0.80497838, -0.12151325, ...,  1.01936424,
         0.85273527, -1.35251779]])

In [94]:
X_test_transformed = sc.transform(X_test)

In [95]:
X_test_transformed

array([[ 7.83780756e-01, -8.02608638e-01, -1.21513252e-01, ...,
         2.39485830e-01, -2.76992891e-01,  9.00710022e-01],
       [-8.48527817e-01,  2.66826029e-01, -1.21513252e-01, ...,
         3.60392889e-02, -5.71704586e-01,  9.00710022e-01],
       [-1.20999685e-01,  1.61106189e+00, -1.21513252e-01, ...,
         1.18890302e+00,  1.09832835e+00,  9.00710022e-01],
       ...,
       [-1.94962700e-03,  1.04542943e+00,  5.90992483e+00, ...,
         5.44655641e-01,  1.65074652e-01, -6.01441854e-01],
       [ 4.26630582e-01, -8.02608638e-01, -1.21513252e-01, ...,
         8.49825452e-01,  6.07142194e-01, -1.35251779e+00],
       [-5.76035462e-01, -8.02608638e-01, -1.21513252e-01, ...,
         1.03854802e-01, -4.73467354e-01, -6.01441854e-01]])

## Model - Linear Regression model

In [96]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
## Model Fitting / Training 

lr.fit(X_train_transformed, Y_train)

LinearRegression()

In [97]:
print("Training Score ", lr.score(X_train_transformed, Y_train))

Training Score  0.8157923757296903


In [99]:
print("Testing Score ", lr.score(X_test_transformed, Y_test))

Testing Score  0.7917767934361519


In [52]:
prediction = lr.predict(X_test)

In [53]:
lr.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

In [100]:
lr.coef_

array([-4.34129477e+13, -5.01532401e+13,  3.29720281e+02, -8.34335736e+03,
        1.05330999e+17,  3.83098776e+16,  3.48143480e+03,  2.32872248e+02,
        1.01321305e+17,  6.42334923e+02,  1.64677724e+03,  1.54357272e+03,
        1.81231849e+03,  1.09529466e+04, -3.49285644e+03,  5.72826142e+13,
       -2.20291851e+03, -4.68346694e+03,  5.13252553e+03, -3.36783406e+03,
       -4.51016998e+12, -8.02167535e+03,  4.70604404e+03, -3.80420820e+01,
        3.34145737e+02,  1.08200659e+03,  6.03545112e+03,  2.29087121e+04,
       -5.64552319e+02,  2.33992359e+03,  7.56282097e+03, -9.93157270e+16,
        3.03552451e+03,  1.31546230e+04,  1.66660352e+03, -1.45036914e+03])

In [54]:
lr.coef_

array([ 4.01833742e+01,  4.85714846e+01,  3.00262412e+01, -1.21013332e+04,
        2.19855163e+01, -3.40158338e+00,  1.10348178e+03, -1.95358292e+01,
        1.08869516e+00, -7.27912282e+00, -1.84847959e+03, -4.40892990e+03,
        2.32391507e+01,  6.30320374e+03, -9.59089765e+00,  2.78779587e+01,
       -5.38006517e+03, -1.84936297e+04,  5.50301957e-01, -1.77590267e+01,
       -6.08769001e+01, -1.56265286e+02,  2.81546899e+01, -1.84481340e+00,
        1.95217383e+02,  1.59991369e+01,  5.76461920e+03,  1.57633598e+04,
        6.05394137e+01,  2.12696313e+01,  3.06105994e+03,  1.96726281e+01,
        1.47930264e+01,  3.96920408e+02,  1.09555110e+02, -8.76190042e+02])

In [55]:
lr.intercept_


713088.2087231963

In [ ]:
#R2 = SSReg / SSRtotal


In [108]:
housing_data.head()

1stFlrSF  2ndFlrSF  3SsnPorch Alley  BedroomAbvGr BldgType BsmtCond  \
0     856.0     854.0        0.0  None             3     1Fam       TA   
1    1262.0       0.0        0.0  None             3     1Fam       TA   
2     920.0     866.0        0.0  None             3     1Fam       TA   
3     961.0     756.0        0.0  None             3     1Fam       Gd   
4    1145.0    1053.0        0.0  None             4     1Fam       TA   

  BsmtExposure  BsmtFinSF1  BsmtFinSF2  ... ScreenPorch Street  TotRmsAbvGrd  \
0           No       706.0         0.0  ...         0.0   Pave             8   
1           Gd       978.0         0.0  ...         0.0   Pave             6   
2           Mn       486.0         0.0  ...         0.0   Pave             6   
3           No       216.0         0.0  ...         0.0   Pave             7   
4           Av       655.0         0.0  ...         0.0   Pave             9   

   TotalBsmtSF Utilities  WoodDeckSF YearBuilt YearRemodAdd YrSold SalePrice  
0        856.0    AllPub         0.0      2003         2003   2008  208500.0  
1       1262.0    AllPub       298.0      1976         1976   2007  181500.0  
2        920.0    AllPub         0.0      2001         2002   2008  223500.0  
3        756.0    AllPub         0.0      1915         1970   2006  140000.0  
4       1145.0    AllPub       192.0      2000         2000   2008  250000.0  

[5 rows x 80 columns]

In [109]:
housing_data.BsmtCond.unique()

array(['TA', 'Gd', 'None', 'Fa'], dtype=object)

In [119]:
from sklearn.preprocessing import LabelEncoder  , OneHotEncoder
lr = LabelEncoder()
BsmtCond_num = lr.fit_transform(housing_data.BsmtCond)

In [118]:
BsmtCond_num = pd.DataFrame(BsmtCond_num)
BsmtCond_num[0].unique()

array([3, 1, 2, 0])

In [140]:
data= housing_data['BsmtCond'].values

ohe = OneHotEncoder(categories='auto')
BsmtCond_onehot = ohe.fit_transform(data.reshape(-1,1)).toarray()

In [142]:
BsmtCond_onehot

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])